version: '3.8'

services:
  gateway-server:
    build: ./gateway-server
    ports:
      - "3000:3000"
    env_file:
      - ./gateway-server/.env
    depends_on:
      - auth-server
      - event-server

  auth-server:
    build: ./auth-server
    ports:
      - "4000:4000"
    env_file:
      - ./auth-server/.env
    depends_on:
      - mongo

  event-server:
    build: ./event-server
    ports:
      - "5000:5000"
    env_file:
      - ./event-server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
